package com.ft9.view.panel;

import java.awt.JobAttributes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;

import com.ft9.annotation.Menu;
import com.ft9.bean.VendorBean;
import com.ft9.dao.impl.VendorDao;
import com.ft9.service.IVendorService;
import com.ft9.service.ServiceManager;
import com.ft9.service.ServiceNotFoundException;
import com.ft9.service.impl.VendorService;
import com.ft9.util.BeanUtil;
import com.ft9.util.ViewUtil;
import com.ft9.view.NameConverter;
import com.ft9.view.ViewManager;
import com.ft9.view.panel.subFunctionPanel.AddVendorPanel;

/**
*
* @author apple
*/
@Menu(name = "Vendor", fatherName = "Manage")

public class ManageVendorPanel extends javax.swing.JPanel implements ActionListener, PropertyChangeListener {

   /**
	 * 
	 */
	private static final long serialVersionUID = 2L;
/**
	 * 
	 */
	private IVendorService vendorService = null;
	/**
    * Creates new form ManageProductPanel
	 * @throws ServiceNotFoundException 
    */
   public ManageVendorPanel() throws ServiceNotFoundException {
       vendorService = (VendorService) ServiceManager.getService("Vendor");
	   initComponents();
	   initDatas();
	   setActionListener();
   }
   
   private void initDatas(){
	   jTable1.setModel(ViewUtil.transferBeanList2DefaultTableModel(vendorService.getAllVendorInfo(), "Vendor"));
	   
   }
   
   private void setActionListener(){
   	this.addPropertyChangeListener("Refresh", this);
   	jButtonDelete.addActionListener(this);
   	jButtonAdd.addActionListener(this);
   	jButtonUpdate.addActionListener(this);
   	jButtonSearch.addActionListener(this);
   }
   

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jButton1 = ViewManager.createGoHomeButton();
       jTextField1 = new javax.swing.JTextField();
       jLabel1 = new javax.swing.JLabel();
       jButtonSearch = new javax.swing.JButton();
       jButtonAdd = new javax.swing.JButton();
       jButtonDelete = new javax.swing.JButton();
       jButtonUpdate = new javax.swing.JButton();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTable1 = ViewUtil.createUneditableTable();
       jComboBox1 = new javax.swing.JComboBox<>();

       jButton1.setText("Back");

       jTextField1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField1ActionPerformed(evt);
           }
       });

       jLabel1.setText("Key Word:");

       jButtonSearch.setText("Search");
       jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButtonSearchActionPerformed(evt);
           }
       });

       jButtonAdd.setText("Add");

       jButtonDelete.setText("Delete");

       jButtonUpdate.setText("Modify");

//       jTable1.setModel(new javax.swing.table.DefaultTableModel(
//           new Object [][] {
//               {null, null, null, null},
//               {null, null, null, null},
//               {null, null, null, null},
//               {null, null, null, null}
//           },
//           new String [] {
//               "Title 1", "Title 2", "Title 3", "Title 4"
//           }
//       ));
       jScrollPane1.setViewportView(jTable1);

       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(NameConverter.getTitleArr("Vendor")));
       jComboBox1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBox1ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(59, 59, 59)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(23, 23, 23))
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jButtonAdd)
                               .addGap(31, 31, 31)
                               .addComponent(jButtonDelete)
                               .addGap(33, 33, 33)
                               .addComponent(jButtonUpdate))
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabel1)
                               .addGap(10, 10, 10)
                               .addComponent(jTextField1)
                               .addGap(18, 18, 18)
                               .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addGap(10, 10, 10)
                               .addComponent(jButtonSearch)))
                       .addGap(434, 434, 434))))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(54, 54, 54)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jLabel1)
                   .addComponent(jButtonSearch)
                   .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButtonAdd)
                   .addComponent(jButtonDelete)
                   .addComponent(jButtonUpdate))
               .addGap(18, 18, 18)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(23, 23, 23))
       );
   }// </editor-fold>                        

   private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
   }                                          

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           


   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButtonSearch;
   private javax.swing.JButton jButtonAdd;
   private javax.swing.JButton jButtonDelete;
   private javax.swing.JButton jButtonUpdate;
   private javax.swing.JComboBox<String> jComboBox1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration                   
@Override
public void propertyChange(PropertyChangeEvent arg0) {
	// TODO Auto-generated method stub
	if(this.getClientProperty("Refresh") != null && this.getClientProperty("Refresh").equals("True")){
		initDatas();
		putClientProperty("Refresh", "false");
	}
	
}

@Override
public void actionPerformed(ActionEvent arg0) {
	// TODO Auto-generated method stub
	Object source = arg0.getSource();
	if (source == jButtonAdd){
		try {
			ViewManager.goToSubFunctionScreen(new AddVendorPanel());
		} catch (ServiceNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}else if (source == jButtonDelete){
		deleteExcu();
	}else if (source == jButtonSearch){
		searchExcu();
	}else if (source == jButtonUpdate){
		modifyExcu();
	}
	
}

private void modifyExcu() {
	// TODO Auto-generated method stub
	List<HashMap<String, String>> selectedData = ViewUtil.getSelectedData(jTable1);
	if (selectedData.size() != 1){
		JOptionPane.showMessageDialog(null, "Please Choose 1 Vendor To Modify !", "Error", JOptionPane.ERROR_MESSAGE);
		return;
	}
	Map<String, String> selectedMap = NameConverter.convertViewMap2PhysicMap(selectedData.get(0), "Vendor");
	VendorBean selectedVendorBean = new VendorBean();
	BeanUtil.transMap2Bean(selectedMap, selectedVendorBean);
	try {
		ViewManager.goToSubFunctionScreen(new AddVendorPanel(selectedVendorBean, AddVendorPanel.UPDATE_NEW_VENDOR));
	} catch (ServiceNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	
}

private void searchExcu() {
	// TODO Auto-generated method stub
	String key, valuelike;
	key = (String) jComboBox1.getSelectedItem();
	key = NameConverter.convertViewName2PhysicName("Vendor", key);
	valuelike = jTextField1.getText();
	List<VendorBean> searchResult = vendorService.searchVendorByKey(key, valuelike);
	jTable1.setModel(ViewUtil.transferBeanList2DefaultTableModel(searchResult, "Vendor"));
	
}

private void deleteExcu() {
	// TODO Auto-generated method stub
	List<HashMap<String, String>> selectedData = ViewUtil.getSelectedData(jTable1);
	int option = 1;
	if (selectedData.size() < 1){
		JOptionPane.showMessageDialog(null, "Please At Least Choose One Vendor To Delete !", "Error", JOptionPane.ERROR_MESSAGE);
		return;
	}
	option = JOptionPane.showConfirmDialog(null, "Are You Sure To Delete The " + selectedData.size() + " Vendor ?", "Info", JOptionPane.YES_NO_OPTION);
	if (option == 1){
		return;
	}else {
		for (HashMap<String, String> map:selectedData){
			vendorService.deleteVendorByMap(NameConverter.convertViewMap2PhysicMap(map, "Vendor"));
		}
	}
	this.initDatas();s
	
}
}


















