package com.ft9.view.panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;

import com.ft9.annotation.Menu;
import com.ft9.bean.DiscountBean;
import com.ft9.bean.ProductBean;
import com.ft9.service.IProductService;
import com.ft9.service.ServiceManager;
import com.ft9.service.ServiceNotFoundException;
import com.ft9.service.impl.ProductService;
import com.ft9.util.BeanUtil;
import com.ft9.util.ViewUtil;
import com.ft9.view.NameConverter;
import com.ft9.view.ViewManager;
import com.ft9.view.panel.subFunctionPanel.AddDiscountPanel;
import com.ft9.view.panel.subFunctionPanel.AddProductPanel;

@Menu(name = "Product", fatherName = "Manage")

/**
 *
 * @author hippo
 */
public class ManageProductPanel extends javax.swing.JPanel implements ActionListener,PropertyChangeListener{

    /**
     * Creates new form ManageProductPanel
     */
	IProductService productService=null;
    public ManageProductPanel() throws ServiceNotFoundException {
    	productService=(ProductService)ServiceManager.getService("Product");
        initComponents();
        initDatas();
        setActionListener();
       // searchTxtField.setText("");
    }
    
    private void initDatas(){
    	jTable1.setModel(ViewUtil.transferBeanList2DefaultTableModel(productService.getAllProducts(),"Product"));
    }
    
    private void setActionListener(){
    	this.addPropertyChangeListener("Refresh", this);
    	deleteBtn.addActionListener(this);
    	addBtn.addActionListener(this);
    	searchBtn.addActionListener(this);
    	modifyBtn.addActionListener(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        goHomeButton = ViewManager.createGoHomeButton();
        searchTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = ViewUtil.createUneditableTable();
        jComboBox1 = new javax.swing.JComboBox<>();


        searchTxtField.setText("");
        searchTxtField.setSize(72, 21);
        jLabel1.setText("Key Word:");

        searchBtn.setText("Search");
    

        addBtn.setText("Add");

        deleteBtn.setText("Delete");

        modifyBtn.setText("Modify");

        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(NameConverter.getTitleArr("Product")));
   

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                //.addGap(70, 70, 70)
                                .addComponent(goHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(53, 53, 53)
                                .addComponent(deleteBtn)
                                .addGap(53, 53, 53)
                                .addComponent(modifyBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(searchTxtField, 77, 77, 77)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(searchBtn)))
                        .addGap(434, 434, 434))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(searchBtn)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn)
                    .addComponent(modifyBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>                        

    @Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO 自动生成的方法存根
		Object source=arg0.getSource();
		if(source==deleteBtn){
			deleteExec();
		}else if(source==addBtn){
			try {
				ViewManager.goToSubFunctionScreen(new AddProductPanel());
			} catch (Exception e) {
				// TODO 自动生成的 catch 块
				e.printStackTrace();
			}
		}else if(source==searchBtn){
			searchExec();
		}else if(source==modifyBtn){
			modifyExec();
		}
		
	}
	
	private void modifyExec(){
		try {
			List<HashMap<String,String>> selectedDatas=ViewUtil.getSelectedData(jTable1);
			if(selectedDatas.size()!=1){
				JOptionPane.showMessageDialog(null, "Please select 1 item to Modify", "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}
			Map<String,String>selectedMap=NameConverter.convertViewMap2PhysicMap(selectedDatas.get(0), "Product");
			ProductBean selectedProductBean=new ProductBean();
			BeanUtil.transMap2Bean(selectedMap, selectedProductBean);
			ViewManager.goToSubFunctionScreen(new AddProductPanel(selectedProductBean,AddProductPanel.MODIFY_DISCOUNT));
		} catch (ServiceNotFoundException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
	}
	private void deleteExec(){
		List<HashMap<String,String>> selectedDatas=ViewUtil.getSelectedData(jTable1);
		if(selectedDatas.size()<1){
			JOptionPane.showMessageDialog(null, "Please select at least 1 item to delete", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		int options=JOptionPane.showConfirmDialog(null, "Are you ready to delete this "+selectedDatas.size()+"Items?", "Info",JOptionPane.YES_NO_OPTION);
		if(options==1){
			return;
		}
		for(HashMap<String,String> map:selectedDatas){
			
			productService.deleteProductByMap(NameConverter.convertViewMap2PhysicMap(map, "Product"));
		}
		this.initDatas();
	}
	
	private void searchExec(){
		String key=jComboBox1.getSelectedItem().toString();
		key=NameConverter.convertViewName2PhysicName("Product", key);
		String valueLike=searchTxtField.getText();
		List<ProductBean>searchResult=productService.searchProductByKey(key, valueLike);
		jTable1.setModel(ViewUtil.transferBeanList2DefaultTableModel(searchResult,"Product"));
	}

	@Override
	public void propertyChange(PropertyChangeEvent arg0) {
		// TODO 自动生成的方法存根
		if(this.getClientProperty("Refresh")!=null&&this.getClientProperty("Refresh").equals("True")){
			 initDatas();
			 putClientProperty("Refresh", "False");
		}
		
		
	}

    // Variables declaration - do not modify                     
    private javax.swing.JButton goHomeButton;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchTxtField;
    // End of variables declaration                   
}
