package com.ft9.view.panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.HashMap;
import java.util.List;

import javax.swing.JOptionPane;

import com.ft9.annotation.Menu;
import com.ft9.service.IStoreKeeperService;
import com.ft9.service.ServiceManager;
import com.ft9.service.ServiceNotFoundException;
import com.ft9.service.impl.StoreKeeperService;
import com.ft9.util.ViewUtil;
import com.ft9.view.NameConverter;
import com.ft9.view.ViewManager;
import com.ft9.view.panel.subFunctionPanel.AddStorekeeperPanel;

/**
*
* @author apple
*/
@Menu(name = "Manage", fatherName = "StoreKeeper")
public class StorekeeperManagePanel extends javax.swing.JPanel implements PropertyChangeListener, ActionListener {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private IStoreKeeperService storekeeperService = null;
	/**
     * Creates new form StorekeeperManagePanel
	 * @throws ServiceNotFoundException 
     */
    public StorekeeperManagePanel() throws ServiceNotFoundException {
        storekeeperService = (StoreKeeperService) ServiceManager.getService("StoreKeeper");
    	initComponents();
    	initDatas();
    	setActionListener();
    }
    
    public void initDatas(){
    	//Get the Storekeeper info into the table.
    	jTable1.setModel(ViewUtil.transferBeanList2DefaultTableModel(storekeeperService.getAllStoreKeeper(), "StoreKeeper"));
    }
    
    private void setActionListener(){
    	this.addPropertyChangeListener("Refresh",this);
    	jButtonAdd.addActionListener(this);
    	jButtonDelete.addActionListener(this);
    	
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        //make the table uneditable
        jTable1 = ViewUtil.createUneditableTable();
        jButtonBack = ViewManager.createGoHomeButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Title 1", "Title 2", "Title 3", "Title 4"
//            }
//        ));
        jScrollPane1.setViewportView(jTable1);

       // jButtonBack.setText("Back");

        jButtonAdd.setText("Add");

        jButtonDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAdd)
                            .addGap(45, 45, 45)
                            .addComponent(jButtonDelete)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGap(547, 547, 547)
                            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		Object source = arg0.getSource();
		// if user presses the "Add button", the screen skip to the AddStorekeeper screen,
		// if user presses other buttons, excute the corresponding functions
		if (source == jButtonAdd){
			try {
				ViewManager.goToSubFunctionScreen(new AddStorekeeperPanel());
			} catch (ServiceNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}else if(source == jButtonDelete){
			deleteExcu();
		}
		
		
	}

	private void deleteExcu() {
		// TODO Auto-generated method stub
		int option;
		List<HashMap<String, String>> selectedData = ViewUtil.getSelectedData(jTable1);
		if (selectedData.size() < 1){
			JOptionPane.showMessageDialog(null, "Please at least choose one storekeeper to delete !", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		option = JOptionPane.showConfirmDialog(null, "Are you sure to delete this " + selectedData.size() + " storekeeper?", "Confirm", JOptionPane.YES_NO_OPTION);
		if (option == 1){
			return;
		}else{
			for (HashMap<String, String> map: selectedData){
				storekeeperService.deleteUserByName(map.get("Name"));
				
			}
		}
		initDatas();
	}

	@Override
	public void propertyChange(PropertyChangeEvent evt) {
		// TODO Auto-generated method stub
		if (this.getClientProperty("Refresh") != null && this.getClientProperty("Refresh").equals("True")){
			initDatas();
			putClientProperty("Refresh", "False");
		}
		
	}
}
