package com.ft9.view.panel.subFunctionPanel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import com.ft9.bean.VendorBean;
import com.ft9.service.ServiceManager;
import com.ft9.service.ServiceNotFoundException;
import com.ft9.service.impl.VendorService;
import com.ft9.util.ViewUtil;
import com.ft9.view.ViewManager;

/**
*
* @author apple
*/
public class AddVendorPanel extends javax.swing.JPanel {

   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public static final int ADD_NEW_VENDOR = 0X01;
	public static final int UPDATE_NEW_VENDOR = 0X02;

	private int type = ADD_NEW_VENDOR;
	private VendorService vendorService = null;
	private VendorBean vendorBean = null;
/**
    * Creates new form AddVendorPanel
 * @throws ServiceNotFoundException 
    */
   public AddVendorPanel() throws ServiceNotFoundException {
       initComponents();
       this.clearAllTxtArea();
       vendorService = (VendorService) ServiceManager.getService("Vendor");
   }
   
   public AddVendorPanel(VendorBean _vendorBean, int _type) throws ServiceNotFoundException{
	   initComponents();
	   this.clearAllTxtArea();
       vendorService = (VendorService) ServiceManager.getService("Vendor");
       this.vendorBean = _vendorBean;
       this.type = _type;
       this.setData();
       if (type == UPDATE_NEW_VENDOR){
    	   jButton3.setText("Modify");
       }
   }

   private void setData() {
	// TODO Auto-generated method stub
	   if (vendorBean == null){
		   return;
	   }else if (vendorBean.getName() != null){
		   jTextField1.setText(vendorBean.getName());
	   }else if (vendorBean.getDescription() != null){
		   jTextField2.setText(vendorBean.getDescription());
	   }
	   jTextField1.setEnabled(false);
	
}



/**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jButton1 = ViewManager.createGoBackButton();
       jButton2 = ViewManager.createGoHomeButton();
       jLabel1 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       jTextField2 = new javax.swing.JTextField();
       jButton3 = new javax.swing.JButton();
       jButton4 = new javax.swing.JButton();

     

       jLabel1.setText("Name");

       jTextField1.setText("jTextField1");

       jLabel2.setText("Description");

       jTextField2.setText("jTextField2");

       jButton3.setText("Confirm");
       
       jButton3.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			confirmExcu();
			
		}


	});

       jButton4.setText("Clear");
       
       jButton4.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			clearAllTxtArea();
			
		}
	});

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(232, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jButton3)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                               .addComponent(jButton4))
                           .addGroup(layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                   .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                               .addGap(36, 36, 36)
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                       .addGap(202, 202, 202)))
               .addGap(26, 26, 26))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(24, 24, 24)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(97, 97, 97)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
               .addGap(44, 44, 44)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(139, 139, 139))
       );
   }// </editor-fold>                        


   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   // End of variables declaration  
   
   
   private void clearAllTxtArea() {
		// TODO Auto-generated method stub
		if (type == ADD_NEW_VENDOR){
			jTextField1.setText("");
		}
		jTextField2.setText("");
		this.clearAllTxtAreaError();
	}

	private void clearAllTxtAreaError() {
		// TODO Auto-generated method stub
		ViewUtil.clearJTextError(jTextField1);
		ViewUtil.clearJTextError(jTextField2);
		
	}
	
	
   private boolean checkIfAllFulfilled(){
	   if (ViewUtil.isJTextEmpty(jTextField1)){
		   ViewUtil.setJTextError(jTextField1);
		   return false;
	   }else if (ViewUtil.isJTextEmpty(jTextField2)){
		   ViewUtil.setJTextError(jTextField2);
		   return false;
	   }
	   return true;
   }
   
	private void confirmExcu() {
		// TODO Auto-generated method stub
		this.clearAllTxtAreaError();
		this.vendorBean = generateDataBean();
		if (vendorBean == null){
			return;
		}
		if (type == ADD_NEW_VENDOR){
			if (vendorService.isCodeExist(jTextField1.getText())){
				JOptionPane.showMessageDialog(null, "This Vendor Already Exist!", "ERROR", JOptionPane.ERROR_MESSAGE);
				ViewUtil.setJTextError(jTextField1);
				return;
			}
			if (vendorService.addNewVendor(vendorBean)){
				JOptionPane.showMessageDialog(null, "Your Information Added Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
			}
		}else if (type == UPDATE_NEW_VENDOR){
			if (vendorService.updateVendor(vendorBean)){
				JOptionPane.showMessageDialog(null, "Your Information updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
				ViewManager.goBack();
			}
		}
		clearAllTxtArea();
	}
	
   private VendorBean generateDataBean(){
	   if (!checkIfAllFulfilled()){
		   JOptionPane.showMessageDialog(null, "Every Column Can't Be Null !", "Error", JOptionPane.ERROR_MESSAGE);
		   return null;
	   }else if (type == ADD_NEW_VENDOR && vendorService.isCodeExist(jTextField1.getText())){
		   ViewUtil.setJTextError(jTextField1);
		   JOptionPane.showMessageDialog(null, "The Vendor Name Has Already Existed", "Error", JOptionPane.ERROR_MESSAGE);
		   return null;
	   }
	   VendorBean vendorBean = new VendorBean();
	   vendorBean.setName(jTextField1.getText());
	   vendorBean.setDescription(jTextField2.getText());
	   return vendorBean;
	   
   }
   
   
   
   
}



